// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import 'utils/dependencies.dart';

/// Fixed length byte array
class XdrByteArrayFixed4 extends XdrFixedByteArray {
  XdrByteArrayFixed4(Uint8List wrapped) : super(wrapped);

  @override
  int size = 4;

  static XdrByteArrayFixed4 fromXdr(XdrDataInputStream stream) {
    return XdrFixedByteArray.fromXdr(stream, 4) as XdrByteArrayFixed4;
  }
}
