// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import 'utils/dependencies.dart';

/// Fixed length byte array
class XdrByteArrayFixed16 extends XdrFixedByteArray {
  XdrByteArrayFixed16(Uint8List wrapped) : super(wrapped);

  @override
  int size = 16;

  static XdrByteArrayFixed16 fromXdr(XdrDataInputStream stream) {
    return XdrFixedByteArray.fromXdr(stream, 16) as XdrByteArrayFixed16;
  }
}
