// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import 'utils/dependencies.dart';

/// Fixed length byte array
class XdrByteArrayFixed32 extends XdrFixedByteArray {
  XdrByteArrayFixed32(Uint8List wrapped) : super(wrapped);

  @override
  int size = 32;

  static XdrByteArrayFixed32 fromXdr(XdrDataInputStream stream) {
    return XdrFixedByteArray.fromXdr(stream, 32) as XdrByteArrayFixed32;
  }
}
